# Importing Libraries 

In [1]:
import tensorflow as tf
import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import MinMaxScaler 
import sys
np.set_printoptions(threshold=sys.maxsize)

# Loading Data

In [2]:
data = pd.read_excel("todoData.xlsx", date_parser=True)
data.head()

Date  bread  egg  waffles  ...  potatoes  garlic  ginger  pepper
0 2018-01-01      1    1        1  ...         1       1       1       0
1 2018-01-02      1    0        0  ...         0       0       0       0
2 2018-01-03      0    0        0  ...         0       0       0       0
3 2018-01-04      1    1        0  ...         0       0       0       0
4 2018-01-05      1    1        0  ...         0       1       1       1

[5 rows x 30 columns]

# Training Data

In [3]:
#train data before 2019-06-30

training_data = data[data["Date"]< "2019-06-30"].copy()
training_data

Date  bread  egg  waffles  ...  potatoes  garlic  ginger  pepper
0   2018-01-01      1    1        1  ...         1       1       1       0
1   2018-01-02      1    0        0  ...         0       0       0       0
2   2018-01-03      0    0        0  ...         0       0       0       0
3   2018-01-04      1    1        0  ...         0       0       0       0
4   2018-01-05      1    1        0  ...         0       1       1       1
..         ...    ...  ...      ...  ...       ...     ...     ...     ...
540 2019-06-25      1    1        1  ...         0       1       1       0
541 2019-06-26      1    0        0  ...         0       0       0       0
542 2019-06-27      0    0        0  ...         0       0       0       0
543 2019-06-28      1    1        0  ...         0       0       0       0
544 2019-06-29      1    1        0  ...         0       1       1       1

[545 rows x 30 columns]

# Testing Data 

In [4]:
#test data after 2019-06-29

testing_data = data[data["Date"]>"2019-06-29"].copy()
testing_data

Date  bread  egg  waffles  ...  potatoes  garlic  ginger  pepper
545 2019-06-30      0    0        0  ...         0       0       0       0
546 2019-07-01      1    0        0  ...         0       0       0       0
547 2019-07-02      1    1        0  ...         0       0       0       0
548 2019-07-03      0    1        0  ...         0       1       1       0
549 2019-07-04      1    0        0  ...         0       0       0       1
..         ...    ...  ...      ...  ...       ...     ...     ...     ...
725 2019-12-27      1    0        0  ...         0       0       0       0
726 2019-12-28      1    0        0  ...         0       0       0       0
727 2019-12-29      1    1        0  ...         0       0       0       0
728 2019-12-30      0    0        0  ...         0       1       1       0
729 2019-12-31      1    0        0  ...         0       0       0       1

[185 rows x 30 columns]

# Removing Date Columns From Train Data

In [5]:
#removing unnecessary columns i.e "Date" removed

train_data = training_data.drop(["Date"], axis=1)
train_data

bread  egg  waffles  butter  milk  ...  onion  potatoes  garlic  ginger  pepper
0        1    1        1       1     1  ...      1         1       1       1       0
1        1    0        0       0     1  ...      0         0       0       0       0
2        0    0        0       0     1  ...      0         0       0       0       0
3        1    1        0       0     1  ...      0         0       0       0       0
4        1    1        0       0     1  ...      0         0       1       1       1
..     ...  ...      ...     ...   ...  ...    ...       ...     ...     ...     ...
540      1    1        1       1     1  ...      1         0       1       1       0
541      1    0        0       1     1  ...      0         0       0       0       0
542      0    0        0       0     1  ...      0         0       0       0       0
543      1    1        0       0     1  ...      0         0       0       0       0
544      1    1        0       0     1  ...      0         0       1       1       1

[545 rows x 29 columns]

# Normalizing Values

In [6]:
#normalizing values 

scaler = MinMaxScaler()
train_data = scaler.fit_transform(train_data)
train_data

array([[1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 1., 0., 0., 0., 1., 1.,
        0., 0., 0., 0., 1., 1., 0., 1., 1., 1., 1., 1., 0.],
       [1., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1.,
        0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 1., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1., 1.,
        0., 0., 0., 1., 1., 1., 0., 1., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1.,
        1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1.,
        0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1

# Preparing Training Data 

In [0]:
x_train = []
y_train = []

In [0]:
# training on 3 days then predciting 4th value

for i in range (3, train_data.shape[0]):
    x_train.append(train_data[i-3:i])
    y_train.append(train_data[i])
    


In [0]:
x_train , y_train = np.array(x_train), np.array(y_train)

In [10]:
x_train.shape

(542, 3, 29)

In [11]:
y_train.shape

(542, 29)

# Building Model

In [12]:
# building LSTM network

from tensorflow.keras import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout

regressor = Sequential()

# regressor.add(LSTM(units = 60, activation = "relu", return_sequences = True, input_shape= (x_train.shape[1],29)))
regressor.add(LSTM(units = 120, activation = "relu", return_sequences = True, input_shape= (x_train.shape[1],29)))
regressor.add(Dropout(0.2))

# regressor.add(LSTM(units = 60, activation = "relu", return_sequences = True))
regressor.add(LSTM(units = 140, activation = "relu", return_sequences = True))
regressor.add(Dropout(0.3))

# regressor.add(LSTM(units = 80, activation = "relu", return_sequences=True))
regressor.add(LSTM(units = 150, activation = "relu", return_sequences = True))
regressor.add(Dropout(0.3))

regressor.add(LSTM(units = 180, activation = "relu"))
# regressor.add(Dropout(0.2))
regressor.add(Dense(29, activation='sigmoid'))

Instructions for updating:
If using Keras pass *_constraint arguments to layers.


In [13]:
regressor.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm (LSTM)                  (None, 3, 120)            72000     
_________________________________________________________________
dropout (Dropout)            (None, 3, 120)            0         
_________________________________________________________________
lstm_1 (LSTM)                (None, 3, 140)            146160    
_________________________________________________________________
dropout_1 (Dropout)          (None, 3, 140)            0         
_________________________________________________________________
lstm_2 (LSTM)                (None, 3, 150)            174600    
_________________________________________________________________
dropout_2 (Dropout)          (None, 3, 150)            0         
_________________________________________________________________
lstm_3 (LSTM)                (None, 180)               2

#compiling the regressor model


In [14]:

regressor.compile(optimizer="adam", loss="binary_crossentropy", metrics=["acc"])

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


#training the the model


In [15]:

regressor.fit(x_train, y_train, epochs=120, batch_size=8)

Train on 542 samples
Epoch 1/120
542/542 [==============================] - 5s 10ms/sample - loss: 0.5635 - acc: 0.7687
Epoch 2/120
542/542 [==============================] - 3s 6ms/sample - loss: 0.4951 - acc: 0.7750
Epoch 3/120
542/542 [==============================] - 3s 5ms/sample - loss: 0.4863 - acc: 0.7760
Epoch 4/120
542/542 [==============================] - 3s 6ms/sample - loss: 0.4796 - acc: 0.7799
Epoch 5/120
542/542 [==============================] - 3s 5ms/sample - loss: 0.4653 - acc: 0.7867
Epoch 6/120
542/542 [==============================] - 3s 6ms/sample - loss: 0.4421 - acc: 0.8009
Epoch 7/120
542/542 [==============================] - 3s 6ms/sample - loss: 0.4123 - acc: 0.8138
Epoch 8/120
542/542 [==============================] - 3s 5ms/sample - loss: 0.3849 - acc: 0.8255
Epoch 9/120
542/542 [==============================] - 3s 5ms/sample - loss: 0.3620 - acc: 0.8422
Epoch 10/120
542/542 [==============================] - 3s 6ms/sample - loss: 0.3441 - acc: 0.84

# Preparing Test Data 

In [0]:
# preparing test data 

# we need to have last 3 days of training data to predict the first test data

past_3_days = training_data.tail(3)

df = past_3_days.append(testing_data, ignore_index = True)



In [17]:
df

Date  bread  egg  waffles  ...  potatoes  garlic  ginger  pepper
0   2019-06-27      0    0        0  ...         0       0       0       0
1   2019-06-28      1    1        0  ...         0       0       0       0
2   2019-06-29      1    1        0  ...         0       1       1       1
3   2019-06-30      0    0        0  ...         0       0       0       0
4   2019-07-01      1    0        0  ...         0       0       0       0
..         ...    ...  ...      ...  ...       ...     ...     ...     ...
183 2019-12-27      1    0        0  ...         0       0       0       0
184 2019-12-28      1    0        0  ...         0       0       0       0
185 2019-12-29      1    1        0  ...         0       0       0       0
186 2019-12-30      0    0        0  ...         0       1       1       0
187 2019-12-31      1    0        0  ...         0       0       0       1

[188 rows x 30 columns]

## Removing Date Columns From Test Data

In [18]:
df = df.drop(["Date"],axis=1)
df

bread  egg  waffles  butter  milk  ...  onion  potatoes  garlic  ginger  pepper
0        0    0        0       0     1  ...      0         0       0       0       0
1        1    1        0       0     1  ...      0         0       0       0       0
2        1    1        0       0     1  ...      0         0       1       1       1
3        0    0        0       0     1  ...      0         0       0       0       0
4        1    0        0       1     1  ...      0         0       0       0       0
..     ...  ...      ...     ...   ...  ...    ...       ...     ...     ...     ...
183      1    0        0       1     1  ...      0         0       0       0       0
184      1    0        0       0     1  ...      0         0       0       0       0
185      1    1        0       0     1  ...      0         0       0       0       0
186      0    0        0       0     1  ...      0         0       1       1       0
187      1    0        0       0     0  ...      1         0       0       0       1

[188 rows x 29 columns]

# Normalizing Values

In [19]:
inputs  = scaler.transform(df)
inputs

array([[0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.,
        0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 1.,
        0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 1., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1.,
        1., 0., 0., 1., 1., 1., 0., 1., 0., 0., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1.,
        0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0.],
       [1., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1.,
        0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0.],
       [1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1

In [0]:
x_test = []
y_test = []

In [0]:
for i in range(3, inputs.shape[0]):
    x_test.append(inputs[i-3:i])
    y_test.append(inputs[i])

In [22]:
x_test, y_test = np.array(x_test), np.array(y_test)
x_test.shape, y_test.shape

((185, 3, 29), (185, 29))

# Prediction

In [0]:
# predicting item
y_pred = regressor.predict(x_test)

In [24]:
y_pred.shape

(185, 29)

In [25]:
y_pred

array([[1.19209290e-07, 3.41564417e-04, 0.00000000e+00, 1.24780655e-01,
        9.99929905e-01, 9.99997139e-01, 0.00000000e+00, 5.99280536e-01,
        2.11540163e-02, 5.69670260e-01, 0.00000000e+00, 0.00000000e+00,
        3.06963921e-06, 8.91053677e-02, 9.99974370e-01, 3.19226384e-02,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 2.68220901e-07, 0.00000000e+00, 9.99998808e-01,
        0.00000000e+00, 1.92046165e-04, 1.08778477e-05, 4.17232513e-06,
        0.00000000e+00],
       [9.99988198e-01, 2.40418315e-03, 1.88230097e-01, 5.08255303e-01,
        9.99963284e-01, 9.99997616e-01, 0.00000000e+00, 1.20172799e-02,
        1.89507008e-03, 1.40747428e-02, 1.96695328e-05, 1.15275383e-04,
        2.98023224e-08, 9.60761905e-02, 5.84820211e-01, 9.91161466e-01,
        2.13921070e-03, 4.98592854e-05, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 9.99994755e-01,
        1.15334988e-05, 2.53584683e-02,

In [26]:
test_loss, test_acc = regressor.evaluate(x_test, y_test)

185/185 [==============================] - 0s 2ms/sample - loss: 0.3020 - acc: 0.9167


In [27]:
test_loss, test_acc 

(0.3020380087800928, 0.91668224)